### ISSUE TITLE
File Metadata not kept after conversion

### ISSUE THREAD

**Issue by cvzalez** [Tichau/FileConverter#15]
After converting an mp3 to aac, I realized several limitations, one is the lack of VBR encoding and the most serious one is that MetaData is not kept after conversion, so Title, Album and other metadata is lost,

**Comment by Tichau** [comment]
Hi,

I will try to reproduce that issue.
What was the version of File Converter you used?

Thanks for the report.

**Comment by Tichau** [comment]
Hi,

The AAC conversion is by default a VBR encoding. I didn't offer the option to force the CBR because I think it is not very compatible (optimized) with this kind of compression. Maybe I should remove the CBR option for mp3 too.

For the AAC tags, I made some researches. It seems that the AAC format doesn't have the possibility to metadata without violating the format.

> AAC can't and won't be able to have tags into themselves. As a consequence, tagging an AAC file is violating the format and nothing makes it understandable by other players.

It seems to exists 2 solutions to tag it anyway.
> * management of AAC format with APEv2 tags, complete and which should normally not create incompatibility problems as they are located at the end of the file and may not be considered as a corruption of the format (as ID3)
> * management of the mp4 format, with its own tag standard. This operation is fully reversible and without any loss of information, the only inconvenient is the lost of compatibility with only AAC readers (as nokia cellphones)"

I will see if I can implement the first solution otherwise, I will add a new output conversion format (m4a) that is the extension for audio mp4.

Source: [foobar documentation](http://eolindel.free.fr/foobar/tags.shtml)

**Comment by Tichau** [comment]
I succeed to write the metadata in ApeV2 format. You will now need to have a player compatible with this format to see the metadata.
I will push the fix asap.
Thanks again for the report
