### ISSUE TITLE
If this project is abandoned, how can we improve it as a community?

### ISSUE THREAD

**Issue by xx88xx** [Tichau/FileConverter#254]
Obviously a lot has changed since 2017. There are a lot of potential fixes and upgrades that could help a lot of people.

For 1, adding native window 11 support in the 1st menu... instead of the second.

I also find the the ico file conversion shrinks the image size right down, while other ico converters maintain the size of the original image.

How can we improve this project as a community? do we take into our own hands? the developer I feel has abandoned it?

**Comment by agret** [comment]
I'm not sure why you think it hasn't changed since 2017, there's a few commits over 2021 and a pull request was merged in 2022.

Since the maintainer is still active any improvements you want to make can be made as a pull request and he should merge it in.

https://github.com/Tichau/FileConverter/commits/integration

**Comment by Cwpute** [comment]
But if i'm not mistaken... there hasn't been any new version available for the public since 2017. Has it ?
https://github.com/Tichau/FileConverter/releases/tag/v1.2.3

**Comment by Tichau** [comment]
Hello everyone, 
You're rigth I did not put a lot of time maintaining this project in the past year. I try to merge stuff from the community when it is proposed in pull requests. I did not find the time to make any proper stabilization and release process since 2017, but I'm currently planning to do a version with all the improvements and fixes from the past years.

**Comment by Cwpute** [comment]
Thanks a lot for your answer!
I'm nwt sure i'll be able to help since i don't have much experience with coding. But if you need some help  with things that don't require such skills, i can lend a hand.
Please do tell us vhat needs to be done :)

**Comment by Tichau** [comment]
I'll close all discussions now that there is a space for that in GitHub: https://github.com/Tichau/FileConverter/discussions
