### ISSUE TITLE
Request: W11 Context Menu Compability

### ISSUE THREAD

**Issue by khutede** [Tichau/FileConverter#376]
Hello! Thank you for this program! I use it almost daily. Any ETA to support the new W11 context menu? That would be a must!

**Comment by Tichau** [comment]
Hello, I tried a bit to do it, but for now I can find a simple way to do it since the library I depend on does not support it and Microsoft seems to want to not support managed assemblies.
Maybe a better way to do it is to rewrite the explorer extension in native language. Any help would be nice on that topic since I will not have a lot of time to do it.

**Comment by Tichau** [comment]
duplicates https://github.com/Tichau/FileConverter/issues/211
