### ISSUE TITLE
Development dead?

### ISSUE THREAD

**Issue by mknepper** [Tichau/FileConverter#65]
I noticed commits are more spaced out over the course of the last couple years. FileConverter isn't dying, is it? 

Edit: Not trying to be a jerk. I couldn't find a more private way to contact the programmer, so I figured opening an issue would be the best way to shed some light on the situation.

**Comment by Tichau** [comment]
File Converter will never die since it's an open source project! You can fork the repository or contribute to this one whenever you want :).

As a reminder, File Converter is a personal project developed in my free time, this is why it's sometimes complicated to find time to improve it.

I have currently no time to allow on this project so it's on pause for now. I'll try to find some time to review and integrate pull request into the `integration` branch (some new features and fixes are already in it).
I'll probably work on it again in a near-ish future ;).
